djangosige/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

from djangosige.configs import DEBUG

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        url(r'^404/$', views.handler404),
        url(r'^500/$', views.handler500),
    ]

djangosige/apps/financeiro/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'financeiro'
urlpatterns = [
    # Lancamentos
    # Gerar lancamento
    url(r'gerarlancamento/$', views.GerarLancamentoView.as_view(),
        name='gerarlancamento'),
    # Lista todos lancamentos
    url(r'lancamentos/$', views.LancamentoListView.as_view(),
        name='listalancamentoview'),

    # Contas a pagar
    # financeiro/contapagar/adicionar/
    url(r'contapagar/adicionar/$',
        views.AdicionarContaPagarView.as_view(), name='addcontapagarview'),
    # financeiro/contapagar/listacontapagar
    url(r'contapagar/listacontapagar/$',
        views.ContaPagarListView.as_view(), name='listacontapagarview'),
    # financeiro/contapagar/editar/
    url(r'contapagar/editar/(?P<pk>[0-9]+)/$',
        views.EditarContaPagarView.as_view(), name='editarcontapagarview'),
    # financeiro/contapagar/listacontapagar/atrasadas/
    url(r'contapagar/listacontapagar/atrasadas/$',
        views.ContaPagarAtrasadasListView.as_view(), name='listacontapagaratrasadasview'),
    # financeiro/contapagar/listacontapagar/hoje/
    url(r'contapagar/listacontapagar/hoje/$',
        views.ContaPagarHojeListView.as_view(), name='listacontapagarhojeview'),

    # Contas a receber
    # financeiro/contareceber/adicionar/
    url(r'contareceber/adicionar/$',
        views.AdicionarContaReceberView.as_view(), name='addcontareceberview'),
    # financeiro/contareceber/listacontapagar
    url(r'contareceber/listacontareceber/$',
        views.ContaReceberListView.as_view(), name='listacontareceberview'),
    # financeiro/contareceber/editar/
    url(r'contareceber/editar/(?P<pk>[0-9]+)/$',
        views.EditarContaReceberView.as_view(), name='editarcontareceberview'),
    # financeiro/contareceber/listacontapagar/atrasadas/
    url(r'contareceber/listacontareceber/atrasadas/$',
        views.ContaReceberAtrasadasListView.as_view(), name='listacontareceberatrasadasview'),
    # financeiro/contareceber/listacontapagar/hoje/
    url(r'contareceber/listacontareceber/hoje/$',
        views.ContaReceberHojeListView.as_view(), name='listacontareceberhojeview'),

    # Pagamentos
    # financeiro/pagamento/adicionar/
    url(r'pagamento/adicionar/$',
        views.AdicionarSaidaView.as_view(), name='addpagamentoview'),
    # financeiro/pagamento/listacontapagar
    url(r'pagamento/listapagamento/$',
        views.SaidaListView.as_view(), name='listapagamentosview'),
    # financeiro/pagamento/editar/
    url(r'pagamento/editar/(?P<pk>[0-9]+)/$',
        views.EditarSaidaView.as_view(), name='editarpagamentoview'),

    # Recebimentos
    # financeiro/recebimento/adicionar/
    url(r'recebimento/adicionar/$',
        views.AdicionarEntradaView.as_view(), name='addrecebimentoview'),
    # financeiro/recebimento/listarecebimento
    url(r'recebimento/listarecebimento/$',
        views.EntradaListView.as_view(), name='listarecebimentosview'),
    # financeiro/recebimento/editar/
    url(r'recebimento/editar/(?P<pk>[0-9]+)/$',
        views.EditarEntradaView.as_view(), name='editarrecebimentoview'),

    # Faturar Pedido de venda
    url(r'faturarpedidovenda/(?P<pk>[0-9]+)/$',
        views.FaturarPedidoVendaView.as_view(), name='faturarpedidovenda'),
    # Faturar Pedido de compra
    url(r'faturarpedidocompra/(?P<pk>[0-9]+)/$',
        views.FaturarPedidoCompraView.as_view(), name='faturarpedidocompra'),

    # Plano de contas
    # financeiro/planodecontas
    url(r'planodecontas/$', views.PlanoContasView.as_view(), name='planocontasview'),
    # financeiro/planodecontas/adicionargrupo/
    url(r'planodecontas/adicionargrupo/$',
        views.AdicionarGrupoPlanoContasView.as_view(), name='addgrupoview'),
    # financeiro/planodecontas/editargrupo/
    url(r'planodecontas/editargrupo/(?P<pk>[0-9]+)/$',
        views.EditarGrupoPlanoContasView.as_view(), name='editargrupoview'),

    # Fluxo de caixa
    # financeiro/fluxodecaixa
    url(r'fluxodecaixa/$', views.FluxoCaixaView.as_view(), name='fluxodecaixaview'),
]

djangosige/apps/fiscal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'fiscal'
urlpatterns = [
    # Nota fiscal saida
    # fiscal/notafiscal/saida/adicionar/
    url(r'notafiscal/saida/adicionar/$',
        views.AdicionarNotaFiscalSaidaView.as_view(), name='addnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/listanotafiscal
    url(r'notafiscal/saida/listanotafiscal/$',
        views.NotaFiscalSaidaListView.as_view(), name='listanotafiscalsaidaview'),
    # fiscal/notafiscal/saida/editar/
    url(r'notafiscal/saida/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalSaidaView.as_view(
    ), name='editarnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/importar/
    url(r'notafiscal/saida/importar/$',
        views.ImportarNotaSaidaView.as_view(), name='importarnotafiscalsaida'),
    # fiscal/notafiscal/saida/gerar/
    url(r'notafiscal/saida/gerar/(?P<pk>[0-9]+)/$',
        views.GerarNotaFiscalSaidaView.as_view(), name='gerarnotafiscalsaida'),

    # Nota fiscal entrada
    # fiscal/notafiscal/entrada/listanotafiscal
    url(r'notafiscal/entrada/listanotafiscal/$',
        views.NotaFiscalEntradaListView.as_view(), name='listanotafiscalentradaview'),
    # fiscal/notafiscal/entrada/editar/
    url(r'notafiscal/entrada/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalEntradaView.as_view(
    ), name='editarnotafiscalentradaview'),
    # fiscal/notafiscal/entrada/importar/
    url(r'notafiscal/entrada/importar/$',
        views.ImportarNotaEntradaView.as_view(), name='importarnotafiscalentrada'),

    # Configuracao NF-e
    url(r'notafiscal/configuracaonotafiscal/$',
        views.ConfiguracaoNotaFiscalView.as_view(), name='configuracaonotafiscal'),

    # Natureza operacao
    # fiscal/naturezaoperacao/adicionar/
    url(r'naturezaoperacao/adicionar/$',
        views.AdicionarNaturezaOperacaoView.as_view(), name='addnaturezaoperacaoview'),
    # fiscal/naturezaoperacao/listanaturezaoperacao
    url(r'naturezaoperacao/listanaturezaoperacao/$',
        views.NaturezaOperacaoListView.as_view(), name='listanaturezaoperacaoview'),
    # fiscal/naturezaoperacao/editar/
    url(r'naturezaoperacao/editar/(?P<pk>[0-9]+)/$', views.EditarNaturezaOperacaoView.as_view(
    ), name='editarnaturezaoperacaoview'),

    # Grupo fiscal
    # fiscal/grupofiscal/adicionar/
    url(r'grupofiscal/adicionar/$',
        views.AdicionarGrupoFiscalView.as_view(), name='addgrupofiscalview'),
    # fiscal/grupofiscal/listagrupofiscalview
    url(r'grupofiscal/listagrupofiscal/$',
        views.GrupoFiscalListView.as_view(), name='listagrupofiscalview'),
    # fiscal/grupofiscal/editar/
    url(r'grupofiscal/editar/(?P<pk>[0-9]+)/$',
        views.EditarGrupoFiscalView.as_view(), name='editargrupofiscalview'),

    # Acoes Nota Fiscal
    # Validar XML nota
    url(r'notafiscal/validar/(?P<pk>[0-9]+)/$',
        views.ValidarNotaView.as_view(), name='validarnotafiscal'),
    # fiscal/notafiscal/emitir/
    url(r'notafiscal/emitir/(?P<pk>[0-9]+)/$',
        views.EmitirNotaView.as_view(), name='emitirnotafiscal'),
    # Clonar nota
    url(r'notafiscal/copiar/(?P<pk>[0-9]+)/$',
        views.GerarCopiaNotaView.as_view(), name='copiarnotafiscal'),
    # Cancelar nota
    url(r'notafiscal/cancelar/(?P<pk>[0-9]+)/$',
        views.CancelarNotaView.as_view(), name='cancelarnotafiscal'),
    # Gerar DANFE
    url(r'notafiscal/gerardanfe/(?P<pk>[0-9]+)/$',
        views.GerarDanfeView.as_view(), name='gerardanfe'),
    # Gerar DANFCE
    url(r'notafiscal/gerardanfce/(?P<pk>[0-9]+)/$',
        views.GerarDanfceView.as_view(), name='gerardanfce'),

    # Comunicacao SEFAZ
    # Consultar cadastro
    url(r'notafiscal/consultarcadastro/$',
        views.ConsultarCadastroView.as_view(), name='consultarcadastro'),
    # Inutilizar notas
    url(r'notafiscal/inutilizarnotas/$',
        views.InutilizarNotasView.as_view(), name='inutilizarnotas'),
    # Consultar nota
    url(r'notafiscal/consultarnota/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    url(r'^notafiscal/consultarnota/(?P<pk>[0-9]+)/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    # Baixar nota
    url(r'notafiscal/baixarnota/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    url(r'^notafiscal/baixarnota/(?P<pk>[0-9]+)/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    # Manifestacao destinatario
    url(r'notafiscal/manifestacaodestinatario/$',
        views.ManifestacaoDestinatarioView.as_view(), name='manifestacaodestinatario'),
]

djangosige/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    # login/
    url(r'^$', views.UserFormView.as_view(), name='loginview'),

    # login/registrar/
    url(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    url(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    url(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    url(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    url(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    url(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    url(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    url(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    url(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    url(r'selecionarempresa/$', views.SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

djangosige/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangosige.apps.base.urls')),
    url(r'^login/', include('djangosige.apps.login.urls')),
    url(r'^cadastro/', include('djangosige.apps.cadastro.urls')),
    url(r'^fiscal/', include('djangosige.apps.fiscal.urls')),
    url(r'^vendas/', include('djangosige.apps.vendas.urls')),
    url(r'^compras/', include('djangosige.apps.compras.urls')),
    url(r'^financeiro/', include('djangosige.apps.financeiro.urls')),
    url(r'^estoque/', include('djangosige.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

djangosige/apps/cadastro/models/cliente.py
# -*- coding: utf-8 -*-

from django.db import models

from decimal import Decimal

from .base import Pessoa

INDICADOR_IE_DEST = [
    ('1', 'Contribuinte ICMS'),
    ('2', 'Contribuinte isento de Inscrição'),
    ('9', 'Não Contribuinte'),
]


class Cliente(Pessoa):
    limite_de_credito = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0.00'), null=True, blank=True)
    indicador_ie = models.CharField(
        max_length=1, choices=INDICADOR_IE_DEST, default='9')
    id_estrangeiro = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        verbose_name = "Cliente"

djangosige/apps/cadastro/models/empresa.py
# -*- coding: utf-8 -*-

import os

from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from .base import Pessoa
from djangosige.apps.login.models import Usuario
from djangosige.configs.settings import MEDIA_ROOT


def logo_directory_path(instance, filename):
    extension = os.path.splitext(filename)[1]
    return 'imagens/empresas/logo_{0}_{1}{2}'.format(instance.nome_razao_social, instance.id, extension)


class Empresa(Pessoa):
    logo_file = models.ImageField(
        upload_to=logo_directory_path, default='imagens/logo.png', blank=True, null=True)
    cnae = models.CharField(max_length=10, blank=True, null=True)
    iest = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        verbose_name = "Empresa"

    @property
    def caminho_completo_logo(self):
        if self.logo_file.name != 'imagens/logo.png':
            return os.path.join(MEDIA_ROOT, self.logo_file.name)
        else:
            return ''

    def save(self, *args, **kwargs):
        # Deletar logo se ja existir um
        try:
            obj = Empresa.objects.get(id=self.id)
            if obj.logo_file != self.logo_file and obj.logo_file != 'imagens/logo.png':
                obj.logo_file.delete(save=False)
        except:
            pass
        super(Empresa, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.nome_razao_social

    def __str__(self):
        return u'%s' % self.nome_razao_social

# Deletar logo quando empresa for deletada


@receiver(post_delete, sender=Empresa)
def logo_post_delete_handler(sender, instance, **kwargs):
    # Nao deletar a imagem default 'logo.png'
    if instance.logo_file != 'imagens/logo.png':
        instance.logo_file.delete(False)


class MinhaEmpresa(models.Model):
    m_empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, related_name='minha_empresa', blank=True, null=True)
    m_usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, related_name='empresa_usuario')

djangosige/apps/cadastro/models/fornecedor.py
# -*- coding: utf-8 -*-

from django.db import models

from .base import Pessoa


class Fornecedor(Pessoa):
    ramo = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "Fornecedor"

djangosige/apps/financeiro/models/plano.py
# -*- coding: utf-8 -*-

from django.db import models

TIPO_GRUPO_ESCOLHAS = (
    (u'0', u'Entrada'),
    (u'1', u'Saída'),
)


class PlanoContasGrupo(models.Model):
    codigo = models.CharField(max_length=6)
    tipo_grupo = models.CharField(max_length=1, choices=TIPO_GRUPO_ESCOLHAS)
    descricao = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Grupo do Plano de Contas"

    def __unicode__(self):
        s = u'%s' % (self.descricao)
        return s

    def __str__(self):
        s = u'%s' % (self.descricao)
        return s


class PlanoContasSubgrupo(PlanoContasGrupo):
    grupo = models.ForeignKey('financeiro.PlanoContasGrupo',
                              related_name="subgrupos", on_delete=models.CASCADE)

djangosige/apps/cadastro/forms/cliente.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from djangosige.apps.cadastro.models import Cliente


class ClienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['limite_de_credito'].localize = True

    class Meta:
        model = Cliente
        fields = ('nome_razao_social', 'tipo_pessoa', 'inscricao_municipal',
                  'limite_de_credito', 'indicador_ie', 'id_estrangeiro', 'informacoes_adicionais', )
        widgets = {
            'nome_razao_social': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_pessoa': forms.RadioSelect(attrs={'class': 'form-control'}),
            'limite_de_credito': forms.TextInput(attrs={'class': 'form-control decimal-mask'}),
            'indicador_ie': forms.Select(attrs={'class': 'form-control'}),
            'inscricao_municipal': forms.TextInput(attrs={'class': 'form-control'}),
            'id_estrangeiro': forms.TextInput(attrs={'class': 'form-control'}),
            'informacoes_adicionais': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome_razao_social': _('Razão Social'),
            'tipo_pessoa': _(''),
            'limite_de_credito': _('Limite de Crédito'),
            'indicador_ie': _('Indicador da IE do Destinatário'),
            'inscricao_municipal': _('Inscrição Municipal'),
            'id_estrangeiro': _('Documento legal (Estrangeiro)'),
            'informacoes_adicionais': _('Informações Adicionais'),
        }

    def save(self, commit=True):
        instance = super(ClienteForm, self).save(commit=False)
        instance.criado_por = self.request.user
        if commit:
            instance.save()
        return instance

djangosige/templates/financeiro/plano/grupo_add.html
{%extends 'base/base.html'%}

{%block title%}Adicionar grupo{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    <div class="title-header">
      <h2>PLANO DE CONTAS</h2>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{% url 'financeiro:planocontasview' %}"><i class="material-icons">&#xE5C4;</i></a>ADICIONAR GRUPO
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'financeiro/plano/grupo_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/tooltip_js.html' %}
  
{% endblock %}

djangosige/templates/financeiro/plano/grupo_edit.html
{%extends 'base/base.html'%}

{%block title%}{{object.descricao}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    <div class="title-header">
      <h2>PLANO DE CONTAS</h2>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{% url 'financeiro:planocontasview' %}"><i class="material-icons">&#xE5C4;</i></a>{{object.descricao}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'financeiro/plano/grupo_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/tooltip_js.html' %}
  
{% endblock %}

djangosige/templates/financeiro/plano/grupo_form.html
<!-- Body-->
<div class="body">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#tab_grupo" data-toggle="tab">GRUPO</a></li>
      <li role="presentation"><a href="#tab_subgrupos" data-toggle="tab">SUBGRUPOS</a></li>
    </ul>
    <div class="tab-content">
      <!-- Tab grupo -->
      <div role="tabpanel" class="tab-pane active" id="tab_grupo">

        {% for field in form %}
        <div class="col-sm-6">
          <div class="form-group">
            <div class="form-line">
              <label>{{field.label}}</label>{% if field.field.required %}<strong style="color:red;"> *</strong>{% endif %}
              {% if field.errors %}<label class="error">{% for error in field.errors %}{{error}}{% endfor %}</label>{% endif %}
              {{field}}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- #Tab grupo -->

      <!-- Tab grupo -->
        <div role="tabpanel" class="tab-pane formset-tab" id="tab_subgrupos">
          <div class="row">
            <h4 style="border-bottom: 1px solid #afabab;">Subgrupos<i class="material-icons" style="font-size: 17px;padding-left:7px;" title="Subgrupos são especificações dos grupos criados, a adição de subgrupos é opcional.">&#xE887;</i></h4>
          </div>
          <div class="row">
          {% include 'formset/formset_fields_sem_padrao.html' %}
          </div>
        </div>

      </div>
      
  </div>

  <button class="btn btn-success foot-btn" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
</div>
<!--#Body-->

djangosige/templates/financeiro/plano/plano.html
{%extends 'base/base.html'%}

{%block title%}Plano de Contas{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
        {% csrf_token %}
        <div class="header">
          <h2>
            PLANO DE CONTAS
          </h2>
          <div class="header-btn">
            <a href="{% url 'financeiro:addgrupoview' %}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
            <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
          </div>
          <div>
            <small>O plano de contas é dividido em entradas (recebimentos) e saídas (pagamentos). Adicione grupos e subgrupos a essas categorias.</small>
          </div>
        </div>

        <div class="body">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tab_entradas" data-toggle="tab">ENTRADA</a></li>
            <li role="presentation"><a href="#tab_saidas" data-toggle="tab">SAIDA</a></li>
          </ul>

            <div class="tab-content">
              <!-- Tab ENTRADAS -->
              <div role="tabpanel" class="tab-pane active" id="tab_entradas">

                <table class="table table-bordered lista-table">
                  <thead>
                    <tr>
                      <th>Código</th>
                      <th>Descrição</th>
                      <th>Categoria</th>
                      <th>Remover</th>
                    </tr>
                  </thead>

                  <tbody>
                  {% if all_grupos_entrada %}
                  {% for ge in all_grupos_entrada %}
                  <tr class="clickable-row plano-grupo-row" data-href="{% url 'financeiro:editargrupoview' ge.id %}">
                    <td class="prevent-click-row" data-toggle="collapse" data-target=".accordion-{{ge.id}}"><i style="vertical-align:inherit;" class="material-icons">&#xE5C5;</i>{{ge.codigo}}</td>
                    <td>{{ge.descricao}}</td>
                    <td>{{ge.get_tipo_grupo_display}}</td>
                    <td class="lista-remove">
                      <input type="checkbox" name="{{ge.id}}" id="remover-entrada-{{ge.id}}"/>
                      <label class="remove-entry-label" for="remover-entrada-{{ge.id}}"></label>
                    </td>
                  </tr>
                    {% for sub in ge.subgrupos.all %}
                  <tr class="plano-subgrupo-row accordion-{{ge.id}} in">
                    <td>{{sub.codigo}}</td>
                    <td>{{sub.descricao}}</td>
                    <td>{{sub.get_tipo_grupo_display}}</td>
                    <td class="lista-remove">
                      <input type="checkbox" name="{{sub.id}}" id="remover-entrada-{{sub.id}}"/>
                      <label class="remove-entry-label" for="remover-entrada-{{sub.id}}"></label>
                    </td>
                  </tr>
                    {% endfor %}

                  {% endfor %}
                  {%else%}
                  {%endif%}
                </tbody>
              </table>

              </div>
              <!-- #Tab ENTRADAS -->

              <!-- Tab SAIDAS -->
              <div role="tabpanel" class="tab-pane" id="tab_saidas">

              <table class="table table-bordered lista-table">
                  <thead>
                    <tr>
                      <th>Código</th>
                      <th>Descrição</th>
                      <th>Categoria</th>
                      <th>Remover</th>
                    </tr>
                  </thead>

                  <tbody>
                  {% if all_grupos_saida %}
                  {% for gs in all_grupos_saida %}
                  <tr class="clickable-row plano-grupo-row" data-href="{% url 'financeiro:editargrupoview' gs.id %}">
                    <td class="prevent-click-row" data-toggle="collapse" data-target=".accordion-{{gs.id}}"><i style="vertical-align:inherit;" class="material-icons">&#xE5C5;</i>{{gs.codigo}}</td>
                    <td>{{gs.descricao}}</td>
                    <td>{{gs.get_tipo_grupo_display}}</td>
                    <td class="lista-remove">
                      <input type="checkbox" name="{{gs.id}}" id="remover-entrada-{{gs.id}}"/>
                      <label class="remove-entry-label" for="remover-entrada-{{gs.id}}"></label>
                    </td>
                  </tr>
                    {% for sub in gs.subgrupos.all %}
                  <tr class="plano-subgrupo-row accordion-{{gs.id}} in">
                    <td>{{sub.codigo}}</td>
                    <td>{{sub.descricao}}</td>
                    <td>{{sub.get_tipo_grupo_display}}</td>
                    <td class="lista-remove">
                      <input type="checkbox" name="{{sub.id}}" id="remover-entrada-{{sub.id}}"/>
                      <label class="remove-entry-label" for="remover-entrada-{{sub.id}}"></label>
                    </td>
                  </tr>
                    {% endfor %}

                  {% endfor %}
                  {%else%}
                  {%endif%}
                </tbody>
              </table>

              </div>
              <!-- #Tab SAIDAS -->

            </div>
          </div>

         

        </div>

        </form>

      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/tooltip_js.html' %}
  
{% endblock %}