djangosige/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

from djangosige.configs import DEBUG

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        url(r'^404/$', views.handler404),
        url(r'^500/$', views.handler500),
    ]

djangosige/apps/fiscal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'fiscal'
urlpatterns = [
    # Nota fiscal saida
    # fiscal/notafiscal/saida/adicionar/
    url(r'notafiscal/saida/adicionar/$',
        views.AdicionarNotaFiscalSaidaView.as_view(), name='addnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/listanotafiscal
    url(r'notafiscal/saida/listanotafiscal/$',
        views.NotaFiscalSaidaListView.as_view(), name='listanotafiscalsaidaview'),
    # fiscal/notafiscal/saida/editar/
    url(r'notafiscal/saida/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalSaidaView.as_view(
    ), name='editarnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/importar/
    url(r'notafiscal/saida/importar/$',
        views.ImportarNotaSaidaView.as_view(), name='importarnotafiscalsaida'),
    # fiscal/notafiscal/saida/gerar/
    url(r'notafiscal/saida/gerar/(?P<pk>[0-9]+)/$',
        views.GerarNotaFiscalSaidaView.as_view(), name='gerarnotafiscalsaida'),

    # Nota fiscal entrada
    # fiscal/notafiscal/entrada/listanotafiscal
    url(r'notafiscal/entrada/listanotafiscal/$',
        views.NotaFiscalEntradaListView.as_view(), name='listanotafiscalentradaview'),
    # fiscal/notafiscal/entrada/editar/
    url(r'notafiscal/entrada/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalEntradaView.as_view(
    ), name='editarnotafiscalentradaview'),
    # fiscal/notafiscal/entrada/importar/
    url(r'notafiscal/entrada/importar/$',
        views.ImportarNotaEntradaView.as_view(), name='importarnotafiscalentrada'),

    # Configuracao NF-e
    url(r'notafiscal/configuracaonotafiscal/$',
        views.ConfiguracaoNotaFiscalView.as_view(), name='configuracaonotafiscal'),

    # Natureza operacao
    # fiscal/naturezaoperacao/adicionar/
    url(r'naturezaoperacao/adicionar/$',
        views.AdicionarNaturezaOperacaoView.as_view(), name='addnaturezaoperacaoview'),
    # fiscal/naturezaoperacao/listanaturezaoperacao
    url(r'naturezaoperacao/listanaturezaoperacao/$',
        views.NaturezaOperacaoListView.as_view(), name='listanaturezaoperacaoview'),
    # fiscal/naturezaoperacao/editar/
    url(r'naturezaoperacao/editar/(?P<pk>[0-9]+)/$', views.EditarNaturezaOperacaoView.as_view(
    ), name='editarnaturezaoperacaoview'),

    # Grupo fiscal
    # fiscal/grupofiscal/adicionar/
    url(r'grupofiscal/adicionar/$',
        views.AdicionarGrupoFiscalView.as_view(), name='addgrupofiscalview'),
    # fiscal/grupofiscal/listagrupofiscalview
    url(r'grupofiscal/listagrupofiscal/$',
        views.GrupoFiscalListView.as_view(), name='listagrupofiscalview'),
    # fiscal/grupofiscal/editar/
    url(r'grupofiscal/editar/(?P<pk>[0-9]+)/$',
        views.EditarGrupoFiscalView.as_view(), name='editargrupofiscalview'),

    # Acoes Nota Fiscal
    # Validar XML nota
    url(r'notafiscal/validar/(?P<pk>[0-9]+)/$',
        views.ValidarNotaView.as_view(), name='validarnotafiscal'),
    # fiscal/notafiscal/emitir/
    url(r'notafiscal/emitir/(?P<pk>[0-9]+)/$',
        views.EmitirNotaView.as_view(), name='emitirnotafiscal'),
    # Clonar nota
    url(r'notafiscal/copiar/(?P<pk>[0-9]+)/$',
        views.GerarCopiaNotaView.as_view(), name='copiarnotafiscal'),
    # Cancelar nota
    url(r'notafiscal/cancelar/(?P<pk>[0-9]+)/$',
        views.CancelarNotaView.as_view(), name='cancelarnotafiscal'),
    # Gerar DANFE
    url(r'notafiscal/gerardanfe/(?P<pk>[0-9]+)/$',
        views.GerarDanfeView.as_view(), name='gerardanfe'),
    # Gerar DANFCE
    url(r'notafiscal/gerardanfce/(?P<pk>[0-9]+)/$',
        views.GerarDanfceView.as_view(), name='gerardanfce'),

    # Comunicacao SEFAZ
    # Consultar cadastro
    url(r'notafiscal/consultarcadastro/$',
        views.ConsultarCadastroView.as_view(), name='consultarcadastro'),
    # Inutilizar notas
    url(r'notafiscal/inutilizarnotas/$',
        views.InutilizarNotasView.as_view(), name='inutilizarnotas'),
    # Consultar nota
    url(r'notafiscal/consultarnota/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    url(r'^notafiscal/consultarnota/(?P<pk>[0-9]+)/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    # Baixar nota
    url(r'notafiscal/baixarnota/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    url(r'^notafiscal/baixarnota/(?P<pk>[0-9]+)/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    # Manifestacao destinatario
    url(r'notafiscal/manifestacaodestinatario/$',
        views.ManifestacaoDestinatarioView.as_view(), name='manifestacaodestinatario'),
]

djangosige/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    # login/
    url(r'^$', views.UserFormView.as_view(), name='loginview'),

    # login/registrar/
    url(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    url(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    url(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    url(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    url(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    url(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    url(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    url(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    url(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    url(r'selecionarempresa/$', views.SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

djangosige/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangosige.apps.base.urls')),
    url(r'^login/', include('djangosige.apps.login.urls')),
    url(r'^cadastro/', include('djangosige.apps.cadastro.urls')),
    url(r'^fiscal/', include('djangosige.apps.fiscal.urls')),
    url(r'^vendas/', include('djangosige.apps.vendas.urls')),
    url(r'^compras/', include('djangosige.apps.compras.urls')),
    url(r'^financeiro/', include('djangosige.apps.financeiro.urls')),
    url(r'^estoque/', include('djangosige.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

djangosige/apps/cadastro/models/fornecedor.py
# -*- coding: utf-8 -*-

from django.db import models

from .base import Pessoa


class Fornecedor(Pessoa):
    ramo = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "Fornecedor"

djangosige/apps/compras/models/compras.py
# -*- coding: utf-8 -*-

from django.db import models
from django.template.defaultfilters import date
from django.core.validators import MinValueValidator
from django.urls import reverse_lazy

from decimal import Decimal

from djangosige.apps.vendas.models import TIPOS_DESCONTO_ESCOLHAS, MOD_FRETE_ESCOLHAS, STATUS_ORCAMENTO_ESCOLHAS
from djangosige.apps.estoque.models import DEFAULT_LOCAL_ID

import locale
locale.setlocale(locale.LC_ALL, '')

STATUS_PEDIDO_COMPRA_ESCOLHAS = (
    (u'0', u'Aberto'),
    (u'1', u'Realizado'),
    (u'2', u'Cancelado'),
    (u'3', u'Importado por XML'),
    (u'4', u'Recebido')
)


class ItensCompra(models.Model):
    produto = models.ForeignKey('cadastro.Produto', related_name="compra_produto",
                                on_delete=models.CASCADE, null=True, blank=True)
    compra_id = models.ForeignKey(
        'compras.Compra', related_name="itens_compra", on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    valor_unit = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    tipo_desconto = models.CharField(
        max_length=1, choices=TIPOS_DESCONTO_ESCOLHAS, null=True, blank=True)
    desconto = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    subtotal = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    inf_ad_prod = models.CharField(max_length=500, null=True, blank=True)

    vicms = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    vipi = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                               MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    p_icms = models.DecimalField(max_digits=5, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    p_ipi = models.DecimalField(max_digits=5, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], null=True, blank=True)

    # Opcoes
    icms_incluido_preco = models.BooleanField(default=False)
    ipi_incluido_preco = models.BooleanField(default=False)
    incluir_bc_icms = models.BooleanField(
        default=False)  # incluir IPI na BC do ICMS
    auto_calcular_impostos = models.BooleanField(default=True)

    @property
    def vprod(self):
        return round(self.quantidade * self.valor_unit, 2)

    def get_total_sem_desconto(self):
        if self.tipo_desconto == '0':
            return self.subtotal + self.desconto
        else:
            tot_sem_desc = (self.subtotal * 100) / (100 - self.desconto)
            return tot_sem_desc

    def get_valor_desconto(self):
        if self.tipo_desconto == '0':
            return self.desconto
        else:
            tot_sem_desc = self.get_total_sem_desconto()
            v_desconto = tot_sem_desc * (self.desconto / 100)
            return v_desconto

    def get_total_impostos(self):
        return sum(filter(None, [self.vicms, self.vipi]))

    def get_total_com_impostos(self):
        total_com_impostos = self.subtotal + self.get_total_impostos()
        return total_com_impostos

    def format_total_impostos(self):
        return locale.format(u'%.2f', self.get_total_impostos(), 1)

    def format_total_com_imposto(self):
        return locale.format(u'%.2f', self.get_total_com_impostos(), 1)

    def format_desconto(self):
        return '{0}'.format(locale.format(u'%.2f', self.get_valor_desconto(), 1))

    def format_quantidade(self):
        return locale.format(u'%.2f', self.quantidade, 1)

    def format_valor_unit(self):
        return locale.format(u'%.2f', self.valor_unit, 1)

    def format_total(self):
        return locale.format(u'%.2f', self.subtotal, 1)

    def format_vprod(self):
        return locale.format(u'%.2f', self.vprod, 1)

    def format_valor_attr(self, nome_attr):
        valor = getattr(self, nome_attr)
        if valor is not None:
            return locale.format(u'%.2f', valor, 1)


class Compra(models.Model):
    # Fornecedor
    fornecedor = models.ForeignKey(
        'cadastro.Fornecedor', related_name="compra_fornecedor", on_delete=models.CASCADE)
    # Transporte
    mod_frete = models.CharField(
        max_length=1, choices=MOD_FRETE_ESCOLHAS, default='9')
    # Estoque
    local_dest = models.ForeignKey(
        'estoque.LocalEstoque', related_name="compra_local_estoque", default=DEFAULT_LOCAL_ID, on_delete=models.PROTECT)
    movimentar_estoque = models.BooleanField(default=True)
    # Info
    data_emissao = models.DateField(null=True, blank=True)
    valor_total = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                      MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    tipo_desconto = models.CharField(
        max_length=1, choices=TIPOS_DESCONTO_ESCOLHAS, default='0')
    desconto = models.DecimalField(max_digits=15, decimal_places=4, validators=[
                                   MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    despesas = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    frete = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    seguro = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    total_icms = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    total_ipi = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                    MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    cond_pagamento = models.ForeignKey(
        'vendas.CondicaoPagamento', related_name="compra_pagamento", on_delete=models.SET_NULL, null=True, blank=True)
    observacoes = models.CharField(max_length=1055, null=True, blank=True)

    def get_total_sem_imposto(self):
        total_sem_imposto = self.valor_total - self.impostos
        return total_sem_imposto

    def get_total_produtos(self):
        itens = ItensCompra.objects.filter(compra_id=self.id)
        tot = 0
        for it in itens:
            tot += it.vprod
        return tot

    def get_total_produtos_estoque(self):
        itens = self.itens_compra.all()
        tot = 0
        for it in itens:
            if it.produto.controlar_estoque:
                tot += it.vprod
        return tot

    def format_total_produtos(self):
        return locale.format(u'%.2f', self.get_total_produtos(), 1)

    @property
    def impostos(self):
        return (self.total_icms + self.total_ipi)

    @property
    def format_data_emissao(self):
        return '%s' % date(self.data_emissao, "d/m/Y")

    def format_valor_total(self):
        return locale.format(u'%.2f', self.valor_total, 1)

    def format_frete(self):
        return locale.format(u'%.2f', self.frete, 1)

    def format_impostos(self):
        return locale.format(u'%.2f', self.impostos, 1)

    def format_vicms(self):
        return locale.format(u'%.2f', self.total_icms, 1)

    def format_vipi(self):
        return locale.format(u'%.2f', self.total_ipi, 1)

    def format_total_sem_imposto(self):
        return locale.format(u'%.2f', self.get_total_sem_imposto(), 1)

    def format_desconto(self):
        if self.tipo_desconto == '0':
            return locale.format(u'%.2f', self.desconto, 1)
        else:
            itens = ItensCompra.objects.filter(compra_id=self.id)
            tot = 0
            for it in itens:
                tot += it.get_total_sem_desconto()

            v_desconto = tot * (self.desconto / 100)
            return locale.format(u'%.2f', v_desconto, 1)

    def format_seguro(self):
        return locale.format(u'%.2f', self.seguro, 1)

    def format_despesas(self):
        return locale.format(u'%.2f', self.despesas, 1)

    def format_total_sem_desconto(self):
        total_sem_desconto = self.valor_total - self.desconto
        return locale.format(u'%.2f', total_sem_desconto, 1)

    def get_forma_pagamento(self):
        if self.cond_pagamento:
            return self.cond_pagamento.get_forma_display()
        else:
            return ""

    def get_local_dest_id(self):
        if self.local_dest:
            return self.local_dest.id
        else:
            return ""

    def get_child(self):
        try:
            return PedidoCompra.objects.get(id=self.id)
        except PedidoCompra.DoesNotExist:
            return OrcamentoCompra.objects.get(id=self.id)

    def __unicode__(self):
        s = u'Compra nº %s' % (self.id)
        return s

    def __str__(self):
        s = u'Compra nº %s' % (self.id)
        return s


class OrcamentoCompra(Compra):
    data_vencimento = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=1, choices=STATUS_ORCAMENTO_ESCOLHAS, default='0')

    class Meta:
        verbose_name = "Orçamento de Compra"

    @property
    def format_data_vencimento(self):
        return '%s' % date(self.data_vencimento, "d/m/Y")

    @property
    def tipo_compra(self):
        return 'Orçamento'

    def edit_url(self):

djangosige/templates/vendas/pedido_venda/pedido_venda_add.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form id="venda_form_add" role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'vendas/venda_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'vendas/venda_jsblock.html' %} 
  
{% endblock %}

djangosige/templates/vendas/pedido_venda/pedido_venda_edit.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}
    {% include 'base/msg_aviso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div class="header-btn">
              <a id="gerar_copia_pedido_venda" href="{% url 'vendas:copiarpedidovenda' object.id %}" class="btn btn-primary">GERAR CÓPIA DO PEDIDO</a>
              <a id="gerar_pdf_venda" href="{% url 'vendas:gerarpdfpedidovenda' object.id %}" class="btn btn-primary">GERAR PDF</a>
              {% if object.status == '0' or object.status == '3' %}
              <a id="faturar_pedido" href="{% url 'financeiro:faturarpedidovenda' object.id %}" class="btn btn-success">FATURAR PEDIDO</a>
              <a id="cancelar_pedido_venda" href="{% url 'vendas:cancelarpedidovenda' object.id %}" class="btn btn-red">CANCELAR</a>
              {% elif object.status == '1'%}
              <a id="gerar_nota_fiscal" href="{% url 'fiscal:gerarnotafiscalsaida' object.id %}" class="btn btn-success">GERAR NOTA FISCAL</a>
              {% endif %}
            </div>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form id="venda_form_edit" role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'vendas/venda_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'vendas/venda_jsblock.html' %} 
  
{% endblock %}

djangosige/templates/vendas/pedido_venda/pedido_venda_list.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              {{title_complete}}
            </h2>
              <div class="header-btn">
                <a href="{{add_url}}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Status</th>
                  <th>Cliente</th>
                  <th>Data de entrega</th>
                  <th>Total</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_pedidos%}
               {% for pedido in all_pedidos %}
               <tr class="clickable-row" data-href="{% url 'vendas:editarpedidovendaview' pedido.id %}">
                <td>{{pedido.id}}</td>
                <td><b>{{pedido.get_status_display}}</b></td>
                <td>{{pedido.cliente|default_if_none:""}}</td>
                <td>{{pedido.format_data_entrega|default_if_none:""}}</td>
                <td>{{pedido.format_valor_total}}</td>
                <td class="lista-remove">
                  <input type="checkbox" name="{{pedido.id}}" id="remover-entrada-{{pedido.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{pedido.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

  </div>
</div>

</div>
</section>


{%endblock%}